# Usage:  Usage: ansible-playbook edb-as-restart-epas.yml --extra-vars "host=ansible-tests pgmajor=11"
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
        asmajor: "{{ pgmajor | default(11) }}"

  tasks:
    - name: Restarting EPAS
      systemd:
        name: edb-as-{{ asmajor }}.service
        state: restarted
        enabled: yes