# Usage:  ansible-playbook edb-rs.stop_eprs7.yml --extra-vars "host=eprs1"

- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Starting EPRS7 as a system service
      systemd:
        name: edb-rs-server.service
        state: stopped
        enabled: yes